config/routes.rb
Rails.application.routes.draw do
  root to: 'recipes#index'
  resources :recipes
  devise_for :users
  get '/users', to: 'users#index'
  get '/users/:id', to: 'users#edit', as: 'edit_user'
  get '/my_recipes', to: 'recipes#my_recipes'
  get '/search', to: 'recipes#search', as: 'search_recipes'
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    can :read, Recipe, public: true
    # can :read, Comments, public: true

    user ||= User.new # guest user (not logged in)
    if user.present?
      if user.is_admin?
        can :manage, :all
      end

      if user.is_moderator?
        can :manage, Recipe #:comments, :
      end

      # Standard user access
      can [:new, :create], Recipe
      can [:edit, :update, :my_recipes, :destroy], Recipe, user_id: user.id
      # can [:edit, :update, :destroy], User, user: user
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    belongs_to :user
    has_one_attached :picture
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :recipes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # rescue_from CanCan::AccessDenied do |exception|
  #   respond_to do |format|
  #     format.json { render nothing: true, status: :not_found }
  #     format.html { redirect_to main_app.root_url, notice: exception.message, status: :not_found }
  #     format.js   { render nothing: true, status: :not_found }
  #   end
  # end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource only: [:new, :edit, :create, :my_recipes, :update, :destroy]

  # GET /recipes
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  def create
    @recipe = current_user.recipes.new(recipe_params)

    if @recipe.save
      redirect_to @recipe, notice: 'Recipe was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /recipes/1
  def update
    if @recipe.update(recipe_params)
      redirect_to @recipe, notice: 'Recipe was successfully updated.'
    else
      render :edit
    end
  end

  def my_recipes
    @recipes = current_user.recipes
  end

  # DELETE /recipes/1
  def destroy
    @recipe.destroy
    redirect_to recipes_url, notice: 'Recipe was successfully destroyed.'
  end

  def search
    if params[:search].blank?
      redirect_to(root_path, alert: 'Empty field!')
    else
      @parameter = params[:search].downcase
      @recipes = Recipe.all.where('lower(title) LIKE :search', search: "%#{@parameter}%")
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:title, :summary, :method, :body, :published, :picture)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :destroy]
  load_and_authorize_resource

  def index
    @users = User.all
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to users_path, notice: "#{@user.username} was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path, notice: "#{@user.username} was successfully deleted."
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:username, :email, :is_admin, :is_moderator)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<p>©2020 Georgia Nic & Josh</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>RecipeApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset="utf-8">
  </head>
  <body>
      <%= render 'shared/navbar' %>

    <main class="container-fluid">
          <%= yield %>
    </main>

    <footer>
      <%= render partial: "layouts/footer" %>
    </footer>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe, local: true) do |form| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>
      <ul>
        <% recipe.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :summary %>
    <%= form.text_field :summary, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :method %>
    <%= form.text_area :method, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :published %>
    <%= form.check_box :published %>
  </div>

  <% if recipe.picture.attached? %>
    <%= (image_tag recipe.picture, size: '300') if recipe.picture.attached? %>
  <% end %>

  <div>
  <%= form.label :picture %>
  <%= form.file_field :picture, accept: 'image/png,image/gif,image/jpeg,image/jpg' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/recipes/_recipe_cards.html.erb
<div class= "recipes" >
  <% @recipes.each do |recipe| %>
    <% if recipe.published %>
      <div class= "recipe">
        <div class= "thumbnail">
          <div class="caption">
            <h3><%= link_to truncate(recipe.title), recipe %></h3>
            <p><%= truncate(recipe.summary, length: 150) %></p>
            <%# <% if is_favourite? %>
              <%#= link_to '', recipe, class: 'glyphicon glyphicon-star' %>
            <%# <% else %>
              <%#= link_to '', recipe, class: 'glyphicon glyphicon-star-empty' %>
            <%# <% end %>
            <% if recipe.picture.attached? %>
              <%= (image_tag(recipe.picture))  if recipe.picture.attached? %>
            <% else %>
              <img src="https://picsum.photos/200" class="card-img-top" alt="Image missing">
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/recipes/edit.html.erb
<div class="container-fluid">
  <h1>Editing Recipe</h1>
  <%= render 'form', recipe: @recipe %>
  <%= link_to 'Show', @recipe %> |
  <%= link_to 'Back', :back %>
</div>

app/views/recipes/index.html.erb
<div class="title-container">
  <h1>All Recipes</h1>
  <% if user_signed_in? %>
    <%= link_to 'New Recipe', new_recipe_path, class: "btn btn-default" %>
  <% end %>
</div>
<p id="notice"><%= notice %></p>

<%= render 'recipe_cards' %>

app/views/recipes/my_recipes.html.erb
<p id="notice"><%= notice %></p>

<h1>My Recipes</h1>
<div class= "container" >
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Title</th>
        <th scope="col">Summary</th>
        <th scope="col">Published</th>
        <th scope="col" colspan='3'><%= link_to 'New Recipe', new_recipe_path %></th>
      </tr>
    </thead>
    <tbody>
      <% @recipes.each do |recipe| %>
        <tr>
          <th scope="row"><%= link_to recipe.title, recipe %></th>
          <td><%= recipe.summary %></td>
          <td><%= recipe.published %></td>
          <% if can? :edit, recipe %>
            <td><%= link_to 'Edit', edit_recipe_path(recipe), class: 'btn btn-success' %></td>
          <% end %>
          <% if can? :destroy, recipe %>
            <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/search.html.erb
<div class="title-container">
<h1>Search Results</h1>
</div>
<%= render 'recipe_cards' %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @recipe.title %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @recipe.summary %>
</p>

<% if @recipe.picture.attached? %>
  <%= (image_tag @recipe.picture, class:'show-page-image') if @recipe.picture.attached? %>
<% else %>
  <figure>
    <img src="https://images.unsplash.com/photo-1588503812457-f289d7f27314?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2850&q=80" class='show-page-image' alt="Image missing">
  <% if (current_user == nil) || !(@recipe.user_id == current_user.id) %>
    <figcaption>Oh, It looks like they ate it all before taking a picture 🤦🏽‍♀️</figcaption>
  <% else %>
    <figcaption>Don't eat it all before you take a picture next time 🙅🏻</figcaption>
  <% end %>
  </figure>
<% end %>

<p>
  <strong>Body:</strong>
  <%= @recipe.body %>
</p>

<p>
  <strong>Method:</strong>
  <%= @recipe.method %>
</p>

<% if can? :edit, @recipe %>
<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<% end %>
<% if can? :destroy, @recipe %>
  <%= link_to 'Delete', @recipe, method: :delete, data: { confirm: 'Are you sure?' } %> |
<% end %>
<%= link_to 'Back', :back %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'Eats Good', recipes_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'Recipes', recipes_path, class: "nav-link" %>
      </li>
       <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to 'My Recipes', my_recipes_path, class: "nav-link" %>
      </li>
       <li class="nav-item">
        <%= link_to 'My Account', edit_user_registration_path, class: "nav-link" %>
      </li>
      <% if can? :manage, :all %>
        <li class="nav-item">
          <%= link_to 'User Admin', users_path, class: "nav-link" %>
        </li>
      <% end %>
     <% end%>
    </ul>
    <%= form_tag(search_recipes_path, method: :get,
        class: 'navbar-form navbar-left') do %>
      <div class="input-group">
        <%= search_field_tag :search, params[:search], placeholder: 'Search', class: 'form-control' %>
        <div class="input-group-append">
          <%= button_tag '', class: 'btn btn-outline-info search', type: 'button', name: nil %>
        </div>
      </div>
    <% end %>
        <% if user_signed_in?%>
          <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: "nav-link" %>
        <%else%>
          <%= link_to 'Sign in', new_user_session_path, class: "nav-link" %>
        <%end%>
    </form>
  </div>
</nav>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :username %>
    <%= form.text_field :username, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :is_admin %>
    <%= form.check_box :is_admin %>
  </div>

  <div class="field">
    <%= form.label :is_moderator %>
    <%= form.check_box :is_moderator %>
  </div>

  <div class="actions">
    <%= form.submit 'Save', class: 'btn btn-success' %>
  </div>
<% end %>
<%= link_to 'Cancel', :back %>

app/views/users/edit.html.erb
<div class="container-fluid">
  <h1>Editing <%= @user.username %></h1>
  <%= render 'form', user: @user %>
  <%= link_to 'Back', :back %>
</div>

app/views/users/index.html.erb
<div class="title-container">
  <h1>User Management</h1>
</div>
<p id="notice"><%= notice %></p>

<div class= "container" >
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Email</th>
        <th scope="col">Admin?</th>
        <th scope="col">Mod?</th>
        <th scope="col">Login Attempts</th>
        <th scope="col">Created</th>
        <th scope="col" colspan='3'></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <th scope="row"><%= link_to user.username, users_path(user) %></th>
          <td><%= user.email %></td>
          <td><%= user.is_admin %></td>
          <td><%= user.is_moderator %></td>
          <td><%= user.is_admin %></td>
          <td><%= link_to 'Edit', edit_user_path(user), class: 'btn btn-success' %></td>
          <td><%= link_to 'Destroy', users_path(user), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>